chore: lint, proofread
hrtcat/hrtcat pull request #2
Opened 2023-06-26 05:53 UTC by paenis

i left the actual text in journal and anonymity alone, just changed the md formatting. other stuff has grammar/other fixes

2023-07-04 04:45 UTC, paenis commented
i think this is basically ready

2023-07-23 19:48 UTC, hrtcat requested changes
This is amazing. Thank you thank you thank you. It's a much needed update. One minor issue I saw but once that's added back it's good to merge.

And also, thanks for getting this updated with the latest commit on main. I was just logging on to get it up to date myself!

2023-07-23 19:48 UTC, hrtcat commented on other/properly_sterilized.md
> -## Manufactured by Tyger
looks like this section got dropped accidentally.

2023-07-23 20:03 UTC, paenis commented on other/properly_sterilized.md
> -## Manufactured by Tyger
fixed!

2023-07-23 20:19 UTC, hrtcat approved these changes

2023-07-23 20:20 UTC, merged

2023-07-23 20:20 UTC, hrtcat commented
Awesome! thanks for being our first contributor <3